jobs:
  sorts-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fluidattacks/sorts-extension:latest
    steps:
      - uses: actions/checkout@v1
      - name: Check the commit risk with Sorts
        run: |
          . /opt/venv/bin/activate && python3 /sorts/entrypoint.py $GITHUB_WORKSPACE True 75
name: dev
on:
  pull_request:
    branches: [ main ]
